// Label pools — mirrored from config.py (the Python version).
export const POOLS = {
  "feminine": [
    "smile more",
    "pretty",
    "too emotional",
    "be modest",
    "likable",
    "soft",
    "quiet",
    "nurturing",
    "polite",
    "desirable",
    "graceful",
    "delicate",
    "fragile",
    "agreeable",
    "pleasing",
    "submissive",
    "dainty",
    "passive",
    "decorative",
    "gentle",
    "sweet",
    "meek",
    "self-sacrifice",
    "tame yourself",
    "take up less space",
    "be agreeable",
    "don't be difficult",
    "be soft",
    "look approachable",
    "stay small"
  ],
  "masculine": [
    "strong",
    "leader",
    "dominant",
    "confident",
    "aggressive",
    "ambitious",
    "tough",
    "stoic",
    "powerful",
    "provider",
    "assertive",
    "in control",
    "breadwinner",
    "invulnerable",
    "decisive",
    "competitive",
    "unemotional",
    "self-reliant",
    "imposing",
    "disciplined",
    "rational",
    "fearless",
    "commanding",
    "man up",
    "don't cry",
    "take charge",
    "be logical",
    "no weakness",
    "prove yourself",
    "dominate"
  ],
  "mixed": [
    "too much",
    "difficult",
    "confusing",
    "not enough",
    "perform",
    "explain yourself",
    "choose",
    "readable",
    "wrong",
    "undefined",
    "ambiguous",
    "illegible",
    "pick a side",
    "make up your mind",
    "you don't fit",
    "either/or",
    "in between",
    "neither",
    "transgressive",
    "unclassified",
    "deviant",
    "outlier",
    "non-conforming",
    "resist categorization",
    "beyond the binary"
  ]
};
